### ISSUE TITLE
Conductor's loader should work with exising loader (e.g. it not overwrite define.requireModule)

### ISSUE THREAD

**Issue by kagemusha** [tildeio/conductor.js#40] opened 2013-06-12 20:33 UTC
We patched our conductor as follows:

https://github.com/yapplabs/glazier/commit/58f47d857308a0e5bf0b3ba32c66f2703c3ace53

**Comment by cyril-sf** [comment] 2013-06-13 13:32
This is a duplicate of #29.

**Closed as completed by cyril-sf** 2013-06-13 13:32 UTC
